export const categories = [
  { label: "General", value: "General" },
  { label: "Mathematics", value: "Math" },
  { label: "Physics", value: "Physics" },
  { label: "Chemistry", value: "Chemistry" },
  { label: "Biology", value: "Biology" },
  { label: "Medical", value: "Medical" },
  { label: "Medicine", value: "Medical" },
  { label: "Computer Science", value: "Computer Science" },
  { label: "Programming", value: "Programming" },
  { label: "Language Learning", value: "Language Learning" },
  { label: "History", value: "History" },
  { label: "Geography", value: "Geography" },
  { label: "Engineering", value: "Engineering" },
  { label: "Art", value: "Art" },
  { label: "Literature", value: "Literature" },
  { label: "Music", value: "Music" },
  { label: "Philosophy", value: "Philosophy" },
  { label: "Economics", value: "Economics" },
  { label: "Political Science", value: "Political Science" },
  { label: "Psychology", value: "Psychology" },
  { label: "Sociology", value: "Sociology" },
  { label: "Environmental Science", value: "Environmental Science" },
  { label: "Astronomy", value: "Astronomy" },
  { label: "Law", value: "Law" },
  { label: "Medicine", value: "Medicine" },
  { label: "Business", value: "Business" },
  { label: "Education", value: "Education" },
  { label: "Architecture", value: "Architecture" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Environmental Studies", value: "Environmental Studies" },
  { label: "Oceanography", value: "Oceanography" },
  { label: "Sports Science", value: "Sports Science" },
  { label: "Food Science", value: "Food Science" },
  { label: "Geology", value: "Geology" },
  { label: "Anthropology", value: "Anthropology" },
  { label: "Communication", value: "Communication" },
  { label: "Dentistry", value: "Dentistry" },
  { label: "Fashion Design", value: "Fashion Design" },
  { label: "Veterinary Science", value: "Veterinary Science" },
  { label: "Chemical Engineering", value: "Chemical Engineering" },
  { label: "Physics Engineering", value: "Physics Engineering" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Mechanical Engineering", value: "Mechanical Engineering" },
  { label: "Nursing", value: "Nursing" },
  { label: "Public Health", value: "Public Health" },
  { label: "Social Work", value: "Social Work" },
];
