import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "EduGPTs",
  description:
    "EduGPTs stands as an expansive repository of educational-focused GPTs, offering a comprehensive collection that encompasses the power of Generative Pre-trained Transformers. Designed to empower educational endeavors, EduGPTs serves as an invaluable resource for enhancing teaching, learning, research, and content generation.",
  url: "https://edugpts.vercel.app",
  ogImage: "https://edugpts.vercel.app/opengraph-image",
  creator: {
    name: "Rudrodip",
    url: "https://twitter.com/rds_agi",
  },
  keywords: [
    "EduGPTs",
    "EduGPTs applications",
    "EduGPTs for businesses",
    "EduGPTs for projects",
    "EduGPTs AI agents",
    "EduGPTs use cases",
    "EduGPTs features",
    "EduGPTs functionality",
    "EduGPTs submission",
    "EduGPTs terms of use",
    "EduGPTs open-source projects",
    "EduGPTs licensing",
    "EduGPTs subscription",
    "EduGPTs AI solutions",
    "EduGPTs productivity",
    "EduGPTs innovation",
    "OpenAI",
    "ChatGPT",
    "GPT",
    "GPT-3.5",
    "GPT-3",
    "GPT3.5Turbo",
    "GPT4",
    "GPT4Turbo",
    "GPTs",
    "GPT builder",
    "GPT store",
    "EduGPTs and more",
    "AI solutions",
    "AI applications",
    "AI agents",
    "Artificial Intelligence",
    "Natural Language Processing",
    "Text generation",
    "Language model",
    "AI-powered tools",
    "Innovation in AI",
    "AI technology",
    "Advanced language generation",
    "EduGPTs for businesses",
    "EduGPTs for projects",
    "EduGPTs pricing",
    "EduGPTs features",
    "EduGPTs integration",
    "AI development",
    "GPT-based solutions",
    "Cutting-edge AI",
    "AI for productivity",
    "EduGPTs use cases",
  ],
  links: {
    twitter: "https://twitter.com/justmalhar",
    github: "https://github.com/rudrodip",
  },
};
