import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "TheFirm",
  description:
    "The Firm is a AI Software Starup that is ready to take on any work thrown at it. It is a collection of GPTs working for you. Your role? The Founder and CEO.",
  url: "https://thefirm.vercel.app",
  ogImage: "https://thefirm.vercel.app/og.png",
  creator: {
    name: "Rudrodip",
    url: "https://twitter.com/rds_agi",
  },
  keywords: [
    "TheFirm.ai",
    "AI Software",
    "GPT Virtual Firm",
    "Specialized Roles",
    "Profile Pictures",
    "GPTs",
    "Virtual Company",
    "Founder and CEO",
    "Artificial Intelligence",
    "Next.js Web App",
    "Project Management",
    "AI Start-up",
    "Product Launch",
    "Gumroad",
    "Twitter Marketing",
    "ProductHunt Launch",
    "Role-based GPTs",
    "AI Workforce",
    "Artificial Intelligence Solutions",
    "AI-powered Business",
    "AI Workforce",
    "Virtual Assistant",
    "Machine Learning",
    "Natural Language Processing",
    "Innovative Technology",
    "Virtual Employees",
    "Digital Workforce",
    "Automation",
    "AI Development",
    "Technology Innovation",
    "Human-AI Collaboration",
    "Business Efficiency",
    "AI-driven Tasks",
    "Future of Work",
    "Digital Transformation",
    "Startup Company",
    "Tech Company",
    "AI Projects",
    "Role-based AI",
    "Founder and CEO Role",
    "AI Project Management",
  ],
  links: {
    twitter: "https://twitter.com/justmalhar",
    github: "https://github.com/rudrodip/the-firm",
  },
};
